### ISSUE TITLE
Unable to get a new version of utils.js

### ISSUE THREAD

**Issue by puzzle29** [jackocnr/intl-tel-input#1400]
### Steps to reproduce
1.  I follow this guide: https://github.com/jackocnr/intl-tel-input/blob/master/.github/CONTRIBUTING.md#updating-to-a-new-version-of-libphonenumber. But i got errors.
2. I'm on Ubuntu 22.04
3. `bazel build //:all` works well but `ant -f libphonenumber/javascript/build.xml compile-demo` gives me error

### Actual behaviour
Error : 

```
Buildfile: /var/www/html/libphonenumber-tools/libphonenumber/javascript/build.xml

compile-demo:
     [exec] calcdeps.py: Scanning files...
     [exec] calcdeps.py: Finding Closure dependencies...
     [exec] Traceback (most recent call last):
     [exec]   File "/var/www/html/libphonenumber-tools/libphonenumber/javascript/../../closure-library/closure/bin/calcdeps.py", line 599, in <module>
     [exec]     main()
     [exec]   File "/var/www/html/libphonenumber-tools/libphonenumber/javascript/../../closure-library/closure/bin/calcdeps.py", line 568, in main
     [exec]     deps = CalculateDependencies(search_paths, inputs)
     [exec]   File "/var/www/html/libphonenumber-tools/libphonenumber/javascript/../../closure-library/closure/bin/calcdeps.py", line 238, in CalculateDependencies
     [exec]     ResolveDependencies(require, search_hash, result_list, seen_list)
     [exec]   File "/var/www/html/libphonenumber-tools/libphonenumber/javascript/../../closure-library/closure/bin/calcdeps.py", line 310, in ResolveDependencies
     [exec]     ResolveDependencies(sub_require, search_hash, result_list, seen_list)
     [exec]   File "/var/www/html/libphonenumber-tools/libphonenumber/javascript/../../closure-library/closure/bin/calcdeps.py", line 304, in ResolveDependencies
     [exec]     raise Exception('Missing provider for (%s)' % require)
     [exec] Exception: Missing provider for (goog.array)

BUILD FAILED
/var/www/html/libphonenumber-tools/libphonenumber/javascript/build.xml:103: The following error occurred while executing this line:
/var/www/html/libphonenumber-tools/libphonenumber/javascript/build.xml:23: exec returned: 1

Total time: 2 seconds
```

**Comment by jackocnr** [comment]
Sorry I'm not an expert in this, perhaps someone else can chime in? But I've updated libphonenumber myself for now. Thanks.
