### ISSUE TITLE
CountryOrder is not honoured after search terms removed.

### ISSUE THREAD

**Issue by NickSutton** [jackocnr/intl-tel-input#1644]
### Plugin version
v23.0.10

### Steps to reproduce
1.  Search for a country by typing it's name
2.  Delete the search term.
3.  

### Expected behaviour
I would expect countries listed in the `countryOrder` option to be first in the list.

### Actual behaviour
The country list is in alphabetical order.

### Initialisation options
    separateDialCode: true,
    strictMode: true,
    initialCountry: 'ca',
    countryOrder: ['ca'],
    nationalMode: true,
    utilsScript: "assets/InternationalTel_dev/build/js/utils.js",

I appear to be hitting this on initialisation;
````
TypeError: e[a] is not a function
    at intlTelInput.min.js:16:10141
    at Array.forEach (<anonymous>)
    at f (intlTelInput.min.js:16:10126)
    at intlTelInput.min.js:16:28769
````

**Comment by NickSutton** [comment]
Hadn't updated the import method for utils script.... Doh.
